### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by ryan-pham** [fer/ion-tree-list#14]
When there are more items that can fix the screen you cannot scroll to see them

**Comment by fer** [comment]
@ryan-pham thank you for your feedback! 

Is this happening when these items are nested or vertically? I guess it's happening in both cases?

**Comment by ryan-pham** [comment]
I haven't tried it when its nested. But when the group is toggled you cannot scroll down to view more. It has a "locked to the top" feel.

**Comment by fer** [comment]
Apologies, I think I drove you into confusion with the example I provided in the example webpage [http://fer.github.io/ion-tree-list/](http://fer.github.io/ion-tree-list/).

Native ionic directives 'ion-header' and 'ion-content' that fixes the problem. I just updated the example accordingly.

Let me know if you experience any other aside issues.

**Comment by litingjun2015** [comment]
Hi, 

when I run ionic serve, it's ok. But when I run in my android device, there is scrolling issues. Here is my code:

```
<ion-view view-title="频道" hide-back-button="true" hide-nav-bar="true">

  <div class="bar bar-header bar-stable">
    <button class="button  icon ion-ios-arrow-left" ng-click="myGoBack()"></button>
  </div>

  <ion-content class="list has-header">

    <ion-tree-list items="tasks"  collapsed="true"></ion-tree-list>

  </ion-content>

</ion-view>

```

thanks
tingjun
