### ISSUE TITLE
function called when single item clicked

### ISSUE THREAD

**Issue by bluecitymoon** [fer/ion-tree-list#19]
This is really a awsome framework but, right now I need to add a event when user click every single item in the tree. would you help me on it?

I take a look at the source code and have no idea on how to make it. sorry.

Jerry

**Comment by fer** [comment]
I just implemented in [0.0.7](https://github.com/fer/ion-tree-list/releases/tag/0.0.7) a way to get the clicked value in your controller by listening to `$ionTreeList:ItemClicked`. Get lastest and add to your controller:

```
$scope.$on('$ionTreeList:ItemClicked', function(event, item) {
  // process 'item'
  console.log(item);
});
```

I've updated the [example website](http://fer.github.io/ion-tree-list/) where you can test it as well.

However, if your problem persists (or this fix doesn't fully fit your solution) don't hesitate to contact/reopen this ticket.

Thank you very much for your reporting.
