### ISSUE TITLE
not work for me

### ISSUE THREAD

**Issue by NurdinDev** [fer/ion-tree-list#21]
i add all things but the list not show
and i my lo show :
http://localhost:8100/%7B%7BbaseUrl%7D%7D/ion-tree-list.css

**Comment by walterkahn** [comment]
I'm having the exact same problem.

**Comment by fer** [comment]
Apologies for the delay.

Using Angular markup like {{hash}} in an href attribute will make the link go to the wrong URL if the user clicks it before Angular has a chance to replace the {{hash}} markup with its value. Until Angular replaces the markup the link will be broken and will most likely return a 404 error. The ngHref directive solves this problem.

Check https://docs.angularjs.org/api/ng/directive/ngHref for more info.

Apologies again thank you very much for your feedback. Don't hesitate to let me know if you still have issues.
