### ISSUE TITLE
How to get the selected value in the tree list?

### ISSUE THREAD

**Issue by limmouyleng** [fer/ion-tree-list#22]
Great to get this tree list view. I have tried to implement it in my project as a form input and I found out it is hard for me to get the selected(clicked) value. Can you show me way to set ng-model and get the value that I has clicked on a list before I click save button.

**Comment by fer** [comment]
Hi @limmouyleng, apologies for getting back to this so late.

I've implemented a way to get the clicked value in your controller by listening to $ionTreeList:ItemClicked. Get lastest and add to your controller:

```
$scope.$on('$ionTreeList:ItemClicked', function(event, item) {
  // process 'item'
  console.log(item);
});
```

I've also updated the [example website](http://fer.github.io/ion-tree-list/):

![screen shot 2016-03-13 at 2 05 26 am](https://cloud.githubusercontent.com/assets/21882/13726398/ca5afd42-e8c5-11e5-9c0f-adcbc5d637f0.png)

If your problem persists after updated, please don't hesitate to reopen this ticket.

Thank you very much for your support.
