### ISSUE TITLE
demo source code

### ISSUE THREAD

**Issue by tlm5460** [fer/ion-tree-list#24]
Where can I get the demo source code? thanks!

**Comment by xavierxc14** [comment]
here: https://github.com/fer/ion-tree-list/tree/gh-pages is just a branch.

**Comment by tlm5460** [comment]
thank you!

在 2016-03-10 04:16:06，"Xavier" notifications@github.com 写道：

here: https://github.com/fer/ion-tree-list/tree/gh-pages is just a branch.
