### ISSUE TITLE
Make collapse optional

### ISSUE THREAD

**Issue by tvdstaaij** [fer/ion-tree-list#26]
I need a dynamic tree view where all items are always visible, and the user cannot collapse parts of the tree. Judging from the code, `toggleCollapse` is hardcoded, so I cannot prevent the collapsing without a hack or custom fork. It would be nice if it were possible to do something like `<ion-tree-list collapsible="false" ...>`.

I think this would be fairly trivial to implement, I could try to make a patch myself if you prefer that. Would you merge such a patch?

**Comment by fer** [comment]
I'd suggest you propose a pull request. I am more than happy to have a look very soon and comment/merge your changes.

Thank you very much!
