### ISSUE TITLE
Can the ion-tree-list be combined with a navigation view?

### ISSUE THREAD

**Issue by patrickpirzer** [fer/ion-tree-list#42]
Hello,

I have implemented the ion-tree-list in a web-app (ionic tabs app).
The source for the tree is defined in services.js like that:

```
.factory('VerificationTree', function () {
    var verificationTree = [
        {
            id: 'operator',
            name: 'Operator'
        },
        {
            id: 'type_of_test',
            name: 'Type of test',
        },
        {
            id: 'system',
            name: 'System'
        },
        {
            id: 'component',
            name: 'Component'
        },
        {
            id: 'component_group',
            name: 'Component group',
            tree: [
                {
                    id: 'component2',
                    name: 'Component'
                }
            ]
        }
    ];

    return {
        all: function () {
            return verificationTree;
        }
    };
})

```
In controller.js i try to open another page when i click on a tree-list-item:

```
.controller('VerificationCtrl', function ($scope, VerificationTree) {
    $scope.verificationTree = VerificationTree.all();
    $scope.$on('$ionTreeList:ItemClicked', function (event, item) {
        if (item.id == 'type_of_test') {
            window.open('templates/type-of-test.html');
        };
        //if (item.id == 'component2') {
        //    alert('The ion-tree-list item component2 was clicked');
        //};
    })
})
```

When i click per example on the item with the id "type_of_test", the page type-of-test is opened in another browser tab, but the layout looks strange.
The normal ionic tabs layout is lost.
Can i combine the tree with a navigation view like that and how?

```
var app = angular.module('myApp', ['ionic']);
app.config(function($stateProvider) {
  $stateProvider
  .state('index', {
    url: '/',
    templateUrl: 'home.html'
  })
  .state('type-of-test ', {
    url: '/type-of-test ',
    templateUrl: 'type-of-test .html'
  });
});
```

Thank you.

**Comment by fer** [comment]
Hello @patrickpirzer,

This question seems to be already answered on the following Stackoverflow post and seems about fine to me: http://stackoverflow.com/questions/40489805/is-it-possible-to-combine-ion-tree-list-with-a-navigation-view

I will create a plunkr example whenever I have some spare time to represent this behaviour. 

In the meantime, let me know if this solution works for you please.

**Comment by patrickpirzer** [comment]
Hello @fer,

Thank You for your answer.
The Stackoverflow-question You have linked is - surprise, surprise - mine.
I made it yesterday.

I added a new state in the app.js:

```
    .state('tabs.typeoftest', {
        url: '/type-of-test',
        views: {
            'type-of-test': {
                templateUrl: 'templates/type-of-test.html',
                controller: 'TypeOfTestCtrl'
            }
        }
    })
```

Then i edited the function in controller.js:

```
.controller('VerificationCtrl', function ($scope, $state, VerificationTree) {
    $scope.verificationTree = VerificationTree.all();
    $scope.$on('$ionTreeList:ItemClicked', function (event, item) {
        if (item.id == 'type_of_test') {
            //// Version 1 (Works but the page layout is out of order)
            //alert('The ion-tree-list item type_of_test was clicked');
            //window.open('templates/type-of-test.html');
            // Version 2 (Don't work)
            alert(item.id + ' was clicked');
            $state.go('tabs.typeoftest');
            alert('Now the page should be displayed');
        };
    })
})
```

When i click now on the tree item i get the following error:

ionic.bundle.js:26794 Error: Could not resolve 'tabs.typeoftest' from state 'tab.verification'

Maybe the problem depends on the tab/page verification (= VerificationCtrl) in which i want to open the other tab/page.
Can You help me please?

```
    <ion-tab title="Verification" icon-off="ion-ios-gear-outline" icon-on="ion-ios-gear" href="#/tab/verification">
        <ion-nav-view name="verification"></ion-nav-view>
    </ion-tab>
```

**Comment by patrickpirzer** [comment]
Hello @fer,

I got it almost.
The error happened because i made a mistake in the state.
It's not "tabs.typeoftest" but "tab.typeoftest".

Just one question still left.
For testing the page which i open by clicking on a certain tree item on another page i programmed in tabs.html an ion-tab.
Normally i don't want to see it in the navigation bar.
Is there a possibility to get the same result without the ion-tab?

**Comment by patrickpirzer** [comment]
Hello @fer,

I got it.
Instead of

```
<ion-tab title="Type of test" icon-off="ion-ios-gear-outline" icon-on="ion-ios-gear" href="#/tab/type-of-test">
    <ion-nav-view name="type-of-test"></ion-nav-view>
</ion-tab>
```

i must remove the attributes title, icon-off and icon-on:

```
<ion-tab href="#/tab/type-of-test">
    <ion-nav-view name="type-of-test"></ion-nav-view>
</ion-tab>
```

The tabs are still there, but not visible anymore and can be used for opening of pages in Ionic Tabs.

Thank You very much for Your help.
Your ion-tree-list is a great tool!

**Comment by fer** [comment]
We definitely have few timezones between us (almost no time to answer :)).

Glad to see you managed to solve it. Thank you! You can definitely count this one on you, m8! 

p.s.: still looking for contributors ;)
