### ISSUE TITLE
Naming scheme

### ISSUE THREAD

**Issue by kennynaoh** [fer/ion-tree-list#45]
Hello @fer , I am the member of cdnjs project. We want to host this library. There is a question want to ask about naming scheme. I found that the file `ion-tree-list.js` is source file, but the css file `ion-tree-list.css` is minified file. They are different naming scheme. Would you like to change the naming scheme? For example, change the minified css file `ion-tree-list.css` to `ion-tree-list.min.css`. Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/9340

**Comment by fer** [comment]
Hi @kennynaoh , thank you very much for considering this library for the cdnjs project. 

Please find released version 0.0.11 under this link:

https://github.com/fer/ion-tree-list/releases/tag/v0.0.11

Please don't hesitate to let me know if any other tweak is needed, and many thanks for your support.
